---
#
#
#

alias: Turn on fan when music starts playing
trigger:
  - platform: state
    entity_id: media_player.workout_room
    to: 'playing'
condition:
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: switch.turn_on
    entity_id: switch.workout_fan
