---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
resources:
########################################
  - url: /local/tracker-card.js?v=0.3.0
    type: js
########################################
  - url: /local/monster-card.js?v=0.2.3
    type: js
########################################
  - url: /local/mini-media-player-bundle.js?v=1.0.0
    type: module
########################################
  - url: /local/mini-graph-card-bundle.js?v=0.2.2
    type: module
########################################
  - url: /local/surveillance-card.js?v=0.0.1
    type: module

title: Home
background: center / cover no-repeat url("/local/pictures/background2.jpg") fixed
# resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lighting.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/server.yaml
  - !include lovelace/views/devices.yaml
  - !include lovelace/views/settings.yaml
