---
#
#
#

alias: Turn on candle warmers at 4pm
trigger:
  - platform: time
    at: '16:00:00'
condition:
  - condition: state
    entity_id: group.family
    state: home
action:
  - service: switch.turn_on
    entity_id: switch.candle_warmer
