---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Harmony Off
trigger:
  - platform: state
    entity_id: input_select.living_room_tv
    to: 'Power Off'
action:
  - service: remote.turn_off
    entity_id: remote.living_room_tv
  - service: input_select.select_option
    entity_id: input_select.living_room_tv
    data_template:
      option: "Select Input"
