alias: Netflix paused at night
trigger:
  - platform: state
    entity_id: sensor.shield_playing
    to: 'paused'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.netflix
      state: 'Netflix'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
action:
  - service: scene.turn_on
    entity_id: scene.media_paused
