---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: TV Off
trigger:
  - platform: state
    entity_id: remote.living_room_tv
condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
  - condition: time
    after: '20:00:00'
    before: '01:00:00'
action:
  - service: script.turn_on
    entity_id: script.goodnight
