---
# Simple automation, that turns the lights on as
# soon as someone has walked into our master bathroom.
#

alias: Master Bathroom On
trigger:
  - platform: state
    entity_id: binary_sensor.master_bath_door
    to: 'on'
condition:
  - condition: time
    after: '17:00:00'
    before: '19:59:00'
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: light.turn_on
    data:
      brightness: 255
      entity_id: light.master_bath
