---
#
#
#

alias: Hallway Light On
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    to: 'on'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: scene.turn_on
    entity_id: scene.hallway
