---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Doorbell - Reset Exterior Lights to 35% after Ring after 9PM
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition:
  - condition: time
    after: '21:00:00'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id: light.porch_light
    data:
      brightness: 70
      transition: 60
