---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Doorbell - Turn Exterior Lights to 100% when Motion Detected after 9:00PM
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    to: 'on'
condition:
  - condition: time
    after: '21:00:00'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id: light.porch_light
    data:
      brightness: 254
