---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Turn on porch light when sun sets
trigger:
  - platform: sun
    event: sunset
action:
  - service: light.turn_on
    entity_id: light.porch_light
    data:
      brightness: 254
