---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Porch Light off at midnight
trigger:
  - platform: time
    at: "00:00:00"
action:
  - service: light.turn_off
    entity_id: light.porch_light
    data:
      transition: 60
