---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Turn off kitchen candle warmer at 8pm
trigger:
  - platform: time
    at: '20:00:00'
action:
  - service: switch.turn_off
    entity_id: switch.kitchen_candle
