---
#
#
#

alias: Turn on kitchen lights with motion
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: switch.turn_on
    entity_id: switch.kitchen_lights
