---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Speech Notifications On
trigger:
  - platform: time
    at: "08:00:00"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.speech_notifications
