---
# Simple automation, that turns the lights off
# after a certain amount of time.
#

alias: Speech Notifications Off
trigger:
  - platform: time
    at: "21:01:00"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.speech_notifications
